logging.level:
    org:
        springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
        hibernate:
            type: trace
spring:
    datasource:
        initialization-mode: always
        #url: jdbc:postgresql://localhost:5432/springboot_react_starter
        #username: springboot_react_starter_admin
        #password: changeme
    jpa:
        hibernate:
            ddl-auto: none
        properties.hibernate:
            #dialect: org.hibernate.dialect.PostgreSQL10Dialect
            format_sql: true
        generate-ddl: false
        show-sql: true

portal.application.name: "{{ PORTAL_APPLICATION_NAME }}"

server.use-forward-headers: true
