/**
 * Springboot Angular Starter API
 * This is a sample service using springdoc-openapi-ui and OpenAPI 3.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface StringResponse { 
    value?: string;
}